services:
  xray_client:
    image: teddysun/xray
    container_name: xray_client
    restart: unless-stopped
    ports:
      - "10868:10868"
      - "10869:10869"
    volumes:
      - ${USER_PATH}/network/xray/config.json:/etc/xray/config.json
    environment:
      - TZ=${TZ} 
      
#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    ports:
#      - "8000:8000"
#    volumes:
#      - ${USER_PATH}/network/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ${LIB_PATH}:/lampac/dlna
#    restart: unless-stopped
#    networks:
#      - default
#      - ${USER_NET}

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${USER_PATH}/network/caddy/etc/caddy:/etc/caddy
      - ${USER_PATH}/network/caddy/data:/data
      - ${USER_PATH}/network/caddy/config:/config
    networks:
      - ${USER_NET}

networks:
  default:
    driver: bridge
  ${USER_NET}:
    external: true